; -----------------------------
; Generated by the ENVI Modeler
; ENVI 5.5.2, API 3.4
; -----------------------------
pro test
  compile_opt idl2, hidden
  on_error, 2

  e = ENVI()
  ; ----------------
  ; Input Parameters
  ; ----------------
  parameters_1 = Obj_New('ENVITask', DISPLAY_NAME='Input Parameters')
  hInfo = $
    '{' + $
    '    "name": "input_raster",' + $
    '    "display_name": "Input Raster",' + $
    '    "type": "ENVIRASTERARRAY",' + $
    '    "direction": "INPUT",' + $
    '    "required": true,' + $
    '    "description": "Specify an input raster to process.",' + $
    '    "hidden": false,' + $
    '    "allow_null": false,' + $
    '    "dimensions": "[*]"' + $
    '}'
  oParameter = IDLHydrate(TYPE='ENVIParameterENVIRASTERARRAY', JSON_Parse(hInfo))
  parameters_1.AddParameter, oParameter
  hInfo = $
    '{' + $
    '    "name": "output_path",' + $
    '    "display_name": "Output Directory",' + $
    '    "type": "ENVIURI",' + $
    '    "direction": "INPUT",' + $
    '    "required": false,' + $
    '    "description": "Specific the output directory.",' + $
    '    "hidden": false,' + $
    '    "fold_case": false,' + $
    '    "is_directory": true,' + $
    '    "is_temporary": false' + $
    '}'
  oParameter = IDLHydrate(TYPE='ENVIParameterENVIURI', JSON_Parse(hInfo))
  parameters_1.AddParameter, oParameter
  styleSheet = Hash()
  styleSheet["schema"] = "envitask_3.0"
  styleSheet["show_read_more"] = !false
  ok = envi.UI.SelectTaskParameters(parameters_1, STYLE_SHEET=styleSheet)
  if (ok ne 'OK') then return

  ; --------
  ; Iterator
  ; --------
  foreach iterator_1, parameters_1.input_raster, iterator_1_index do begin
    filename=STRMID(iterator_1.URI,0,STRLEN(iterator_1.URI)-4)
    basename=FILE_BASENAME(filename)
    resname=parameters_1.output_path+basename+'_stack.dat'
    print,resname
    
  endforeach

end